### ISSUE TITLE
Uncle Scott's Simple Southern Style Slaw

### ISSUE THREAD

**Issue by GSDowey** [FoodieNerds/cookbook#1]
Ingredients:
- Basic Ingredients:
   - 1 Whole Cabbage
   - 2 Medium White Onions
   - 1 Cup White Vinegar
   - 1 Cup White Sugar
   - 0.5 TBSP Celery Seeds

- Optional Ingredients:
   - 2 Jalapeno Peppers
   - 1 TSP Smoked Paprika

- Equipment:
   - An air tight container, taller than it is wide preferably, that fits into your fridge
   - A food processor with a shredding blade, or an old-fashioned knuckle-buster
   - A mixer, or a puree blade for your food processor

Directions:
1. Wash and stem the cabbage. Shred the cabbage and transfer to the storage container.
2. Puree the onions. Mix in celery seeds and pulse to just blend.
   2a. If you want to add jalapeno, seed, stem and puree it with the onions.
3. Pour vinegar and sugar over the onion puree and pulse to blend.
4. Pour vinegar mixture over the cabbage. Mix well with your hand until all clumps are gone. You should see that the celery seeds are evenly distributed.
5. Press the cabbage down beneath the liquid. This may take some patience and force, but only use your hands to do this or you can damage the slaw.
6. Seal and store in the fridge for at least 12, and preferably 24 hours.

**Comment by tbookless** [comment]
resolved
